// home
export const SET_REACT_PROJECT = 'SET_REACT_PROJECT';
export const TOGGLE_SPIN = 'TOGGLE_SPIN';
// editor
export const SET_EDITOR_CATALOG = 'SET_EDITOR_CATALOG';
export const RESET_EDITOR_CATALOG = 'RESET_EDITOR_CATALOG';
export const ADD_EDITOR_CATALOG_FILE = 'ADD_EDITOR_CATALOG_FILE';
export const DELETE_EDITOR_CATALOG = 'DELETE_EDITOR_CATALOG';
export const ADD_EDITOR_CONTENT = 'ADD_EDITOR_CONTENT';
export const SET_EDITOR_CONETNT = 'SET_EDITOR_CONETNT';
export const DELETE_EDITOR_CONTENT = 'DELETE_EDITOR_CONTENT';
export const RESET_EDITOR_CONTENT = 'RESET_EDITOR_CONTENT';
export const SET_ACTIVE_CONTENT = 'SET_ACTIVE_CONTENT';
export const RUN_PROJECT = 'RUN_PROJECT';
// ast
export const INIT_DND_AST = 'INIT_DND_AST';
export const INIT_AST = 'INIT_AST';
export const GET_AST = 'GET_AST';
export const SET_AST = 'SET_AST';
export const RESET_AST = 'RESET_AST';
export const DELETE_AST = 'DELETE_AST';
export const SET_AST_ATTRS = 'SET_AST_ATTRS';
export const DELETE_AST_ATTRS = 'DELETE_AST_ATTRS';
export const SET_AST_ATTR_STYLE = 'SET_AST_ATTR_STYLE';
export const SET_AST_ATTR_NAMES = 'SET_AST_ATTR_NAMES';
export const SET_DOUBLE_CLICK_AST = 'SET_DOUBLE_CLICK_AST';
// dnd
export const SET_HOVER_ID = 'SET_HOVER_ID';
export const SET_DRAG_STAT = 'SET_DRAG_STAT';
export const SET_RESIZE_STAT = 'SET_RESIZE_STAT';
// toolbar
export const TOGGLE_EMULATOR = 'TOGGLE_EMULATOR';
export const TOGGLE_EDITOR = 'TOGGLE_EDITOR';
export const TOGGLE_DEVTOOLS = 'TOGGLE_DEVTOOLS';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_EMULATOR_DEVICE = 'TOGGLE_EMULATOR_DEVICE';
export const SET_DEVICE_TYPE = 'SET_DEVICE_TYPE';
export const SET_DEVICE_SIZE = 'SET_DEVICE_SIZE';
export const TOGGLE_TOOLBAR = 'TOGGLE_TOOLBAR';
